# .github/workflows/main.yml
name: Fábrica de Software Automatizada - CI/CD

on:
  push:
    branches:
      - main # Dispara o workflow em push para a branch main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js (v20) e Cache
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json' # package-lock.json está na raiz
   
    - name: Instalar dependências Node.js
      run: npm install

    - name: Corrigir permissões de executáveis (Diagnóstico)
      run: chmod +x ./node_modules/.bin/start-server-and-test && chmod +x ./node_modules/.bin/newman
    # Adiciona permissão de execução para ambos os binários

    # NOVO PASSO DE DIAGNÓSTICO E CORREÇÃO DE PERMISSÃO
    - name: Corrigir permissões de executáveis (Diagnóstico)
      run: |
        chmod +x ./node_modules/.bin/start-server-and-test
        chmod +x ./node_modules/.bin/newman
      # O '|' (pipe) permite comandos multilinhas.
      # Certifique-se de que o caminho está correto, relativo à raiz do repo.

    - name: Executar testes unitários/integração Node.js (Jest)
      run: npm test

    - name: Executar testes de API Node.js (Newman E2E)
      run: npm run test:e2e # Agora o npx está no package.json, o que é o correto
    
    # Restante do workflow (Python e deploys) permanece o mesmo
    # ...
