# .github/workflows/main.yml
name: Fábrica de Software Automatizada - CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js (v20) e Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Instalar dependências Node.js
        run: npm install

      - name: Executar testes unitários/integração Node.js (Jest)
        run: npm test

      - name: Iniciar servidor Node.js em background
        run: npm run start &

      - name: Aguardar servidor Node.js estar pronto (wait-on)
        run: npm install -g wait-on && wait-on http://localhost:3000 -t 60000

      - name: Executar testes de API Node.js (Newman E2E)
        run: npm run test:e2e

  deploy-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success() && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Fazer Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir e Enviar Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-test-app:latest
